
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int RESTO = 2;
  public static final int SOMA = 8;
  public static final int DIFERENTE = 14;
  public static final int EXPONENCIAL = 4;
  public static final int MULTIPLICACAO = 6;
  public static final int FECHABLOCO = 21;
  public static final int MAIORIGUAL = 10;
  public static final int INIT = 23;
  public static final int FOR = 32;
  public static final int NEGACAO = 15;
  public static final int MENORIGUAL = 12;
  public static final int AND = 16;
  public static final int IGUAL = 13;
  public static final int LETRA = 36;
  public static final int OR = 17;
  public static final int RAIZ = 3;
  public static final int FIMLINHA = 22;
  public static final int CONDICIONAL = 27;
  public static final int UNTIL = 31;
  public static final int EOF = 0;
  public static final int ENDING = 24;
  public static final int MAIOR = 9;
  public static final int DESVIOCONDICIONAL = 28;
  public static final int error = 1;
  public static final int ABREPARENTESE = 18;
  public static final int MENOR = 11;
  public static final int VARIAVEL = 33;
  public static final int DIVISAO = 5;
  public static final int SAIDA = 30;
  public static final int ENTRADA = 29;
  public static final int COIN = 35;
  public static final int FECHAPARENTESE = 19;
  public static final int ATRIBUICAO = 25;
  public static final int TORF = 37;
  public static final int END = 26;
  public static final int STRING = 38;
  public static final int ABREBLOCO = 20;
  public static final int SUBTRACAO = 7;
  public static final int BALLOT = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RESTO",
  "RAIZ",
  "EXPONENCIAL",
  "DIVISAO",
  "MULTIPLICACAO",
  "SUBTRACAO",
  "SOMA",
  "MAIOR",
  "MAIORIGUAL",
  "MENOR",
  "MENORIGUAL",
  "IGUAL",
  "DIFERENTE",
  "NEGACAO",
  "AND",
  "OR",
  "ABREPARENTESE",
  "FECHAPARENTESE",
  "ABREBLOCO",
  "FECHABLOCO",
  "FIMLINHA",
  "INIT",
  "ENDING",
  "ATRIBUICAO",
  "END",
  "CONDICIONAL",
  "DESVIOCONDICIONAL",
  "ENTRADA",
  "SAIDA",
  "UNTIL",
  "FOR",
  "VARIAVEL",
  "BALLOT",
  "COIN",
  "LETRA",
  "TORF",
  "STRING"
  };
}

